pragma solidity ^0.5.12;

// ----------------------------------------------------------------------------
// 1. Registration Contract
// Functionality: Manages the registration of oracle nodes, recording initial 
// information such as Oracle ID, staked tokens, and service costs.
// Paper Correspondence: Oracle nodes must register in this contract before joining the network.
// ----------------------------------------------------------------------------
contract Registration {
    struct OracleNode {
        uint id;            // Oracle Node ID
        address addr;       // Oracle Wallet Address
        uint stakedTokens;  // Amount of tokens staked
        uint cost;          // Service cost
        bool isRegistered;  // Registration status flag
    }

    // Mapping to store all registered oracles
    mapping(uint => OracleNode) public oracles;
    
    // Event: Emitted upon successful oracle registration
    event OracleRegistered(uint indexed id, address indexed addr, uint stake);

    // Function to register a new oracle
    function registerOracle(uint _id, uint _stake, uint _cost) public {
        require(!oracles[_id].isRegistered, "Oracle already registered");
        oracles[_id] = OracleNode(_id, msg.sender, _stake, _cost, true);
        emit OracleRegistered(_id, msg.sender, _stake);
    }

    // Function to check if an oracle is valid/registered
    function isOracleValid(uint _id) public view returns (bool) {
        return oracles[_id].isRegistered;
    }
}

// ----------------------------------------------------------------------------
// 2. Request Contract
// Functionality: Handles user service requests and records SLA requirements 
// (e.g., Deadlines).
// Paper Correspondence: Requests generated by users are recorded on-chain, 
// including task descriptions and time constraints.
// ----------------------------------------------------------------------------
contract Request {
    struct ServiceRequest {
        uint requestId;
        uint dataLength;    // Data length / Task workload
        uint deadline;      // Service deadline (SLA)
        uint timestamp;     // Submission timestamp
    }

    mapping(uint => ServiceRequest) public requests;
    event RequestSubmitted(uint indexed requestId, uint length, uint deadline);

    // Function to submit a new service request
    function submitRequest(uint _requestId, uint _dataLength, uint _deadline) public {
        requests[_requestId] = ServiceRequest(_requestId, _dataLength, _deadline, now);
        emit RequestSubmitted(_requestId, _dataLength, _deadline);
    }
}

// ----------------------------------------------------------------------------
// 3. Selection Contract (Invocation Contract)
// Functionality: Stores the ID of the optimal oracle selected by the off-chain DRL model.
// ----------------------------------------------------------------------------
contract Selection {
    uint action; // Stores the selected Oracle ID

    // Corresponds to C1.ReAction within the Python script (Records the Action)
    function ReAction(uint ac) public returns(uint){
        action=ac;
        uint ac_d=action;
        return ac_d;
    }

    // Corresponds to C1.SeAction within the Python script (Selects/Views the Action)
    function SeAction() public view returns(uint){
       uint RecommandAction = action;
       return RecommandAction;
    }
}

// ----------------------------------------------------------------------------
// 4. Verification Contract
// Functionality: Records post-service verification results (Success/Failure) 
// to serve as the basis for subsequent reputation updates.
// Paper Correspondence: Based on off-chain validation results, the status 
// (Success/Fail) is recorded on-chain.
// ----------------------------------------------------------------------------
contract Verification {
    struct VerifyRecord {
        uint requestId;
        uint oracleId;
        bool isSuccess;     // Verification status (True for success)
        uint responseTime;  // Actual response time recorded
    }

    mapping(uint => VerifyRecord) public records;
    event VerificationUploaded(uint indexed requestId, uint indexed oracleId, bool success);

    // Function to upload verification results
    function uploadVerification(uint _requestId, uint _oracleId, bool _isSuccess, uint _responseTime) public {
        records[_requestId] = VerifyRecord(_requestId, _oracleId, _isSuccess, _responseTime);
        emit VerificationUploaded(_requestId, _oracleId, _isSuccess);
    }
}